server:
  port: 8081

spring:
  application:
    name: analyze
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: romaincaron1
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analyze-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.romaincaron.analyze.event,com.romaincaron.data_collection.event

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true