server:
  port: 8080

spring:
  application:
    name: data-collection
  # Datasource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/visionary
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Discovery Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Datasources
datasources:
  sources:
    anilist:
      url: https://graphql.anilist.co
      api-key:
      timeout: 5000

# Constants
constants:
  kafka:
    sync-topic: media-sync-topic